# Use the official Python image from the Docker Hub
FROM python:3.9-slim
# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Python script into the container
COPY hello-world.py .

# Command to run the Python script
CMD ["python", "./hello-world.py"]